import { createContext, useContext, useState, useEffect, useCallback } from "react";

const translations = {
  id: {
    // Nav
    nav_home: "Beranda",
    nav_collections: "Koleksi",
    nav_categories: "Kategori",
    nav_regions: "Daerah",
    nav_orders: "Pesanan Saya",
    nav_search: "Cari",
    nav_cart: "Keranjang",
    nav_profile: "Profil",
    nav_login: "Masuk",
    nav_search_placeholder: "Cari batik, motif, atau daerah...",
    nav_menu_open: "Buka menu",
    nav_menu_close: "Tutup menu",
    language: "Bahasa",

    // Home
    hero_title_1: "Lestarikan Wastra,",
    hero_title_2: "Bangga Berbudaya",
    hero_desc:
      "Temukan keindahan batik dari berbagai daerah di Indonesia. Dukung pengrajin lokal, lestarikan warisan negeri.",
    hero_shop: "Belanja Sekarang",
    hero_explore: "Jelajahi Koleksi",
    trust_authentic: "100% Asli",
    trust_authentic_desc: "Batik asli dari pengrajin lokal",
    trust_artisans: "Pengrajin Lokal",
    trust_artisans_desc: "Memberdayakan dan mendukung UMKM",
    trust_shipping: "Pengiriman Aman",
    trust_shipping_desc: "Packing rapi, pengiriman cepat",
    trust_payment: "Pembayaran Aman",
    trust_payment_desc: "Transaksi aman dan terpercaya",
    section_featured: "Koleksi Unggulan",
    section_regions: "Jelajahi Batik dari Berbagai Daerah",
    section_regions_sub: "Setiap daerah punya cerita dan motif khas",
    section_see_all: "Lihat Semua",
    section_cta_title: "Temukan Batik Impianmu",
    section_cta_desc:
      "Jelajahi ratusan koleksi batik tulis, cap, dan kombinasi dari seluruh nusantara.",
    why_title: "Mengapa Memilih WastraHub?",
    why_sub: "Kami berkomitmen menjaga keaslian dan kualitas setiap helai batik.",
    why_1_title: "Autentik & Berkualitas",
    why_1_desc: "Setiap produk diverifikasi langsung dari pengrajin terpercaya di sentra batik Indonesia.",
    why_2_title: "Edukasi Budaya",
    why_2_desc: "Pelajari sejarah, filosofi motif, dan teknik pembuatan di balik setiap koleksi.",
    why_3_title: "Dukung Pengrajin",
    why_3_desc: "Pembelian Anda langsung mendukung ekonomi kreatif dan pelestarian warisan Nusantara.",

    // Footer
    footer_tagline:
      "Marketplace batik Indonesia sekaligus media edukasi wastra Nusantara. Mendukung pengrajin lokal dan melestarikan warisan budaya.",
    footer_explore: "Jelajahi",
    footer_help: "Bantuan",
    footer_contact: "Kontak",
    footer_about: "Tentang Batik",
    footer_faq: "FAQ",
    footer_howto: "Cara Belanja",
    footer_privacy: "Kebijakan Privasi",
    footer_terms: "Syarat & Ketentuan",
    footer_rights: "Hak cipta dilindungi.",

    // Cart
    cart_title: "Keranjang Belanja",
    cart_empty_title: "Keranjang Kosong",
    cart_empty_desc: "Belum ada produk di keranjang Anda.",
    cart_continue: "Lanjut Belanja",
    cart_items: "item",
    cart_summary: "Ringkasan",
    cart_subtotal: "Subtotal",
    cart_shipping: "Ongkir",
    cart_shipping_calc: "Dihitung di checkout",
    cart_voucher: "Kode voucher",
    cart_apply: "Pakai",
    cart_total: "Total",
    cart_checkout: "Checkout",
    cart_remove: "Hapus",

    // Auth
    login_title: "Masuk",
    login_sub: "Selamat datang kembali di WastraHub",
    login_fail: "Login gagal",
    register_title: "Daftar",
    register_sub: "Buat akun untuk mulai berbelanja batik",
    register_fail: "Registrasi gagal",
    password: "Password",
    password_confirm: "Konfirmasi Password",
    password_mismatch: "Password tidak cocok",
    full_name: "Nama Lengkap",
    email: "Email",
    processing: "Memproses...",
    no_account: "Belum punya akun?",
    has_account: "Sudah punya akun?",
    sign_up: "Daftar",
    sign_in: "Masuk",

    // Collections
    collections_title: "Koleksi Batik",
    collections_filter: "Filter",
    collections_close_filter: "Tutup filter",
    collections_search: "Cari koleksi...",
    collections_category: "Kategori",
    collections_region: "Daerah",
    collections_technique: "Teknik",
    collections_sort: "Urutkan",
    collections_all: "Semua",
    collections_sort_newest: "Terbaru",
    collections_sort_price_asc: "Harga: Terendah",
    collections_sort_price_desc: "Harga: Tertinggi",
    collections_sort_name: "Nama A–Z",
    collections_found: "produk ditemukan",
    collections_empty: "Tidak ada produk yang cocok dengan filter.",
    collections_reset: "Reset filter",

    // Categories
    categories_title: "Kategori Batik",
    categories_sub: "Jelajahi koleksi berdasarkan untuk siapa batik ini cocok.",
    categories_view: "Lihat koleksi",

    // Product detail
    product_not_found: "Produk tidak ditemukan",
    product_back: "Kembali ke koleksi",
    product_add_cart: "Tambah ke Keranjang",
    product_buy_now: "Beli Sekarang",
    product_stock: "Stok",
    product_out_of_stock: "Stok habis",
    product_region: "Daerah",
    product_technique: "Teknik",
    product_material: "Bahan",
    product_description: "Deskripsi",
    product_philosophy: "Filosofi",
    product_care: "Cara Perawatan",
    product_related: "Produk Serupa",
    product_authentic: "Asli",
    product_artisan: "Pengrajin",
    product_secure: "Aman",
    product_fast: "Pengiriman Cepat",
    product_qty: "Jumlah",
    product_reviews: "Ulasan Pembeli",
    product_write_review: "Tulis ulasan",
    product_login_review: "untuk menulis ulasan. Review hanya untuk produk yang sudah dibeli.",
    product_no_reviews: "Belum ada ulasan.",
    product_new: "Baru",
    product_wishlist: "Tambah ke wishlist",

    // Reviews errors
    review_login: "Silakan login terlebih dahulu.",
    review_only_bought: "Kamu hanya bisa review produk yang sudah dibeli.",
    review_already: "Kamu sudah memberikan review untuk produk ini.",
    review_need_comment: "Tulis komentar review-mu.",
    review_need_rating: "Pilih rating 1–5 bintang.",
    review_submit: "Kirim Ulasan",
    review_comment_ph: "Bagikan pengalamanmu...",
    user_default: "Pengguna",

    // Regions
    regions_title: "Jelajahi Batik dari Berbagai Daerah",
    regions_subtitle:
      "Temukan kekayaan tradisi batik di seluruh nusantara. Setiap daerah menceritakan kisah unik melalui motif dan warna.",
    regions_spotlight: "Sorotan Kawasan",
    regions_jateng_title: "Jawa Tengah",
    regions_jateng_desc:
      "Dikenal sebagai jantungnya batik, menampilkan pola rumit dan akar budaya yang dalam. Pilih salah satu sentra di bawah untuk melihat koleksi batik khasnya.",
    regions_see_all: "Lihat Semua Daerah",
    regions_other: "Daerah Lainnya",
    regions_all: "Semua Sentra Batik",
    regions_explore_btn: "Jelajahi Batik",
    regions_collections: "koleksi",
    map_title: "Jelajahi Daerah",
    region_not_found: "Daerah tidak ditemukan",
    region_not_found_desc: "Daerah yang kamu cari tidak ada dalam daftar.",
    region_back: "Kembali ke daftar daerah",
    region_breadcrumb_home: "Beranda",
    region_breadcrumb_regions: "Daerah",
    region_available: "koleksi tersedia",
    region_products: "produk",
    region_empty: "Belum ada produk untuk daerah ini.",
    region_map: "Lokasi di peta",

    // Profile
    profile_title: "Profil Saya",
    profile_name: "Nama",
    profile_email: "Email",
    profile_phone: "No. Telepon",
    profile_save: "Simpan Perubahan",
    profile_saved: "Profil berhasil disimpan",
    profile_change_photo: "Ubah Foto",
    profile_remove_photo: "Hapus Foto",
    profile_upload_hint: "JPG, PNG maks. 2MB",

    // Orders
    orders_title: "Pesanan Saya",
    orders_empty: "Belum ada pesanan di kategori ini.",
    orders_detail: "Detail Pesanan",
    orders_back: "Kembali ke pesanan",
    orders_items: "Item pesanan",
    orders_summary: "Ringkasan",
    orders_subtotal: "Subtotal",
    orders_shipping: "Ongkir",
    orders_total: "Total",
    orders_status: "Status",
    orders_payment: "Pembayaran",
    orders_address: "Alamat pengiriman",
    orders_date: "Tanggal",
    orders_tracking: "No. Resi",
    orders_total_label: "Total Pesanan",
    orders_pay_now: "Bayar Sekarang",
    orders_cancel: "Batalkan",
    orders_track: "Lacak Paket",
    orders_received: "Pesanan Diterima",
    orders_buy_again: "Beli Lagi",
    tab_unpaid: "Belum Dibayar",
    tab_unshipped: "Belum Dikirim",
    tab_undelivered: "Belum Diterima",
    tab_done: "Selesai",
    tab_cancel: "Batalkan / Pengembalian",
    status_cancelled: "Dibatalkan",

    // Search
    search_results: "Hasil pencarian",
    search_for: "untuk",
    search_empty: "Tidak ada hasil. Coba kata kunci lain.",
    search_see_all: "Lihat semua koleksi",

    // About
    about_title: "Tentang Batik",
    about_intro:
      "Batik adalah warisan budaya Indonesia yang diakui UNESCO. WastraHub hadir untuk menghubungkan pengrajin dengan pecinta batik di seluruh dunia.",
    about_history: "Sejarah Batik",
    about_history_p1:
      "Batik telah ada di Nusantara selama berabad-abad. Teknik canting dan malam menciptakan motif yang sarat makna filosofis.",
    about_history_p2:
      "Pada 2009, UNESCO menetapkan batik Indonesia sebagai Warisan Budaya Takbenda. Tradisi ini terus hidup di tangan pengrajin lokal.",
    about_types: "Jenis Batik",
    about_tulis: "Batik Tulis",
    about_tulis_desc: "Dikerjakan dengan canting secara manual. Setiap helai unik dan bernilai seni tinggi.",
    about_cap: "Batik Cap",
    about_cap_desc: "Motif dicap dengan tembaga. Lebih cepat diproduksi, tetap menjaga kualitas motif.",
    about_kombi: "Batik Kombinasi",
    about_kombi_desc: "Perpaduan tulis dan cap untuk detail yang kaya dengan efisiensi produksi.",
    about_print: "Batik Printing",
    about_print_desc: "Teknik modern dengan kualitas cetak tinggi, harga lebih terjangkau.",
    about_preserve: "Pelestarian",
    about_preserve_p:
      "Dengan membeli batik autentik, Anda mendukung pengrajin dan membantu melestarikan warisan budaya untuk generasi mendatang.",

    // Checkout
    checkout_title: "Checkout",
    checkout_shipping: "Alamat Pengiriman",
    checkout_payment: "Metode Pembayaran",
    checkout_order: "Pesanan Anda",
    checkout_place: "Buat Pesanan",
    checkout_name: "Nama penerima",
    checkout_phone: "No. telepon",
    checkout_address: "Alamat lengkap",
    checkout_city: "Kota",
    checkout_postal: "Kode pos",
    checkout_notes: "Catatan (opsional)",
    checkout_bank: "Transfer Bank",
    checkout_ewallet: "E-Wallet",
    checkout_cod: "Bayar di Tempat (COD)",
    checkout_success: "Pesanan berhasil dibuat!",

    // Common
    loading: "Memuat...",
    save: "Simpan",
    cancel: "Batal",
    delete: "Hapus",
    edit: "Ubah",
    add: "Tambah",
    search: "Cari",
    actions: "Aksi",
    close: "Tutup",
    view: "Lihat",
    back: "Kembali",

    // Admin
    admin_login: "Login Admin",
    admin_dashboard: "Dasbor",
    admin_products: "Produk",
    admin_orders: "Pesanan",
    admin_reviews: "Ulasan",
    admin_reports: "Laporan",
    admin_logout: "Keluar",
    admin_revenue: "Pendapatan",
    admin_total_orders: "Total Pesanan",
    admin_active_products: "Produk Aktif",
    admin_avg_rating: "Rating Rata-rata",
    admin_add_product: "Tambah Produk",
    admin_edit_product: "Ubah Produk",
    admin_delete_product: "Hapus Produk",
    admin_product_name: "Nama Produk",
    admin_price: "Harga",
    admin_stock: "Stok",
    admin_category: "Kategori",
    admin_status: "Status",
    admin_recent_orders: "Pesanan Terbaru",
    admin_sales_report: "Laporan Penjualan",
    admin_buyers: "Pembeli",
    admin_reviewers: "Peninjau",
    admin_pending_reviews: "Ulasan Menunggu",
    admin_desc: "Deskripsi",
    admin_code: "Kode",
    admin_date: "Tanggal",
    admin_item: "Item",
  },
  en: {
    nav_home: "Home",
    nav_collections: "Collections",
    nav_categories: "Categories",
    nav_regions: "Regions",
    nav_orders: "My Orders",
    nav_search: "Search",
    nav_cart: "Cart",
    nav_profile: "Profile",
    nav_login: "Sign in",
    nav_search_placeholder: "Search batik, motif, or region...",
    nav_menu_open: "Open menu",
    nav_menu_close: "Close menu",
    language: "Language",

    hero_title_1: "Preserve Wastra,",
    hero_title_2: "Pride in Culture",
    hero_desc:
      "Discover the beauty of batik from regions across Indonesia. Support local artisans and preserve national heritage.",
    hero_shop: "Shop Now",
    hero_explore: "Explore Collection",
    trust_authentic: "100% Authentic",
    trust_authentic_desc: "Genuine batik from local artisans",
    trust_artisans: "Local Artisans",
    trust_artisans_desc: "Empowering and supporting MSMEs",
    trust_shipping: "Safe Shipping",
    trust_shipping_desc: "Careful packing, fast delivery",
    trust_payment: "Secure Payment",
    trust_payment_desc: "Safe and trusted transactions",
    section_featured: "Featured Collection",
    section_regions: "Explore Batik from Every Region",
    section_regions_sub: "Each region has its own story and distinctive motifs",
    section_see_all: "See All",
    section_cta_title: "Find Your Dream Batik",
    section_cta_desc:
      "Browse hundreds of hand-drawn, stamped, and combination batik collections from across the archipelago.",
    why_title: "Why Choose WastraHub?",
    why_sub: "We are committed to authenticity and quality in every piece of batik.",
    why_1_title: "Authentic & Quality",
    why_1_desc: "Every product is verified directly from trusted artisans in Indonesian batik centers.",
    why_2_title: "Cultural Education",
    why_2_desc: "Learn the history, motif philosophy, and crafting techniques behind every collection.",
    why_3_title: "Support Artisans",
    why_3_desc: "Your purchase directly supports the creative economy and preservation of Nusantara heritage.",

    footer_tagline:
      "Indonesian batik marketplace and educational media for Nusantara textiles. Supporting local artisans and preserving cultural heritage.",
    footer_explore: "Explore",
    footer_help: "Help",
    footer_contact: "Contact",
    footer_about: "About Batik",
    footer_faq: "FAQ",
    footer_howto: "How to Shop",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms & Conditions",
    footer_rights: "All rights reserved.",

    cart_title: "Shopping Cart",
    cart_empty_title: "Cart is Empty",
    cart_empty_desc: "You have no products in your cart yet.",
    cart_continue: "Continue Shopping",
    cart_items: "items",
    cart_summary: "Summary",
    cart_subtotal: "Subtotal",
    cart_shipping: "Shipping",
    cart_shipping_calc: "Calculated at checkout",
    cart_voucher: "Voucher code",
    cart_apply: "Apply",
    cart_total: "Total",
    cart_checkout: "Checkout",
    cart_remove: "Remove",

    login_title: "Sign in",
    login_sub: "Welcome back to WastraHub",
    login_fail: "Login failed",
    register_title: "Register",
    register_sub: "Create an account to start shopping for batik",
    register_fail: "Registration failed",
    password: "Password",
    password_confirm: "Confirm Password",
    password_mismatch: "Passwords do not match",
    full_name: "Full Name",
    email: "Email",
    processing: "Processing...",
    no_account: "Don't have an account?",
    has_account: "Already have an account?",
    sign_up: "Sign up",
    sign_in: "Sign in",

    collections_title: "Batik Collection",
    collections_filter: "Filter",
    collections_close_filter: "Close filter",
    collections_search: "Search collection...",
    collections_category: "Category",
    collections_region: "Region",
    collections_technique: "Technique",
    collections_sort: "Sort by",
    collections_all: "All",
    collections_sort_newest: "Newest",
    collections_sort_price_asc: "Price: Low to High",
    collections_sort_price_desc: "Price: High to Low",
    collections_sort_name: "Name A–Z",
    collections_found: "products found",
    collections_empty: "No products match your filters.",
    collections_reset: "Reset filters",

    categories_title: "Batik Categories",
    categories_sub: "Browse collections by who the batik is made for.",
    categories_view: "View collection",

    product_not_found: "Product not found",
    product_back: "Back to collection",
    product_add_cart: "Add to Cart",
    product_buy_now: "Buy Now",
    product_stock: "Stock",
    product_out_of_stock: "Out of stock",
    product_region: "Region",
    product_technique: "Technique",
    product_material: "Material",
    product_description: "Description",
    product_philosophy: "Philosophy",
    product_care: "Care Instructions",
    product_related: "Related Products",
    product_authentic: "Authentic",
    product_artisan: "Artisan",
    product_secure: "Secure",
    product_fast: "Fast Delivery",
    product_qty: "Quantity",
    product_reviews: "Customer Reviews",
    product_write_review: "Write a review",
    product_login_review: "to write a review. Reviews are only for products you have purchased.",
    product_no_reviews: "No reviews yet.",
    product_new: "New",
    product_wishlist: "Add to wishlist",

    review_login: "Please sign in first.",
    review_only_bought: "You can only review products you have purchased.",
    review_already: "You have already reviewed this product.",
    review_need_comment: "Please write your review comment.",
    review_need_rating: "Select a rating from 1–5 stars.",
    review_submit: "Submit Review",
    review_comment_ph: "Share your experience...",
    user_default: "User",

    regions_title: "Explore Batik from Every Region",
    regions_subtitle:
      "Discover the richness of batik traditions across the archipelago. Each region tells a unique story through motifs and colors.",
    regions_spotlight: "Spotlight Region",
    regions_jateng_title: "Central Java",
    regions_jateng_desc:
      "Known as the heart of batik, featuring intricate patterns and deep cultural roots. Choose a center below to see its signature collection.",
    regions_see_all: "See All Regions",
    regions_other: "Other Regions",
    regions_all: "All Batik Centers",
    regions_explore_btn: "Explore Batik",
    regions_collections: "collections",
    map_title: "Explore by Region",
    region_not_found: "Region not found",
    region_not_found_desc: "The region you are looking for is not in the list.",
    region_back: "Back to regions list",
    region_breadcrumb_home: "Home",
    region_breadcrumb_regions: "Regions",
    region_available: "collections available",
    region_products: "products",
    region_empty: "No products for this region yet.",
    region_map: "Location on map",

    profile_title: "My Profile",
    profile_name: "Name",
    profile_email: "Email",
    profile_phone: "Phone",
    profile_save: "Save Changes",
    profile_saved: "Profile saved successfully",
    profile_change_photo: "Change Photo",
    profile_remove_photo: "Remove Photo",
    profile_upload_hint: "JPG, PNG max 2MB",

    orders_title: "My Orders",
    orders_empty: "No orders in this category yet.",
    orders_detail: "Order Detail",
    orders_back: "Back to orders",
    orders_items: "Order items",
    orders_summary: "Summary",
    orders_subtotal: "Subtotal",
    orders_shipping: "Shipping",
    orders_total: "Total",
    orders_status: "Status",
    orders_payment: "Payment",
    orders_address: "Shipping address",
    orders_date: "Date",
    orders_tracking: "Tracking number",
    orders_total_label: "Order Total",
    orders_pay_now: "Pay Now",
    orders_cancel: "Cancel",
    orders_track: "Track Package",
    orders_received: "Order Received",
    orders_buy_again: "Buy Again",
    tab_unpaid: "Unpaid",
    tab_unshipped: "To Ship",
    tab_undelivered: "To Receive",
    tab_done: "Completed",
    tab_cancel: "Cancelled / Return",
    status_cancelled: "Cancelled",

    search_results: "Search results",
    search_for: "for",
    search_empty: "No results. Try another keyword.",
    search_see_all: "See all collections",

    about_title: "About Batik",
    about_intro:
      "Batik is Indonesian cultural heritage recognized by UNESCO. WastraHub connects artisans with batik lovers around the world.",
    about_history: "History of Batik",
    about_history_p1:
      "Batik has existed in the archipelago for centuries. Canting and wax techniques create motifs rich with philosophical meaning.",
    about_history_p2:
      "In 2009, UNESCO inscribed Indonesian batik as Intangible Cultural Heritage. The tradition lives on through local artisans.",
    about_types: "Types of Batik",
    about_tulis: "Hand-drawn Batik",
    about_tulis_desc: "Made with a canting by hand. Each piece is unique and highly artistic.",
    about_cap: "Stamped Batik",
    about_cap_desc: "Motifs stamped with copper blocks. Faster to produce while keeping motif quality.",
    about_kombi: "Combination Batik",
    about_kombi_desc: "A mix of hand-drawn and stamped techniques for rich detail with efficient production.",
    about_print: "Printed Batik",
    about_print_desc: "Modern printing with high quality and more affordable prices.",
    about_preserve: "Preservation",
    about_preserve_p:
      "By buying authentic batik, you support artisans and help preserve cultural heritage for future generations.",

    checkout_title: "Checkout",
    checkout_shipping: "Shipping Address",
    checkout_payment: "Payment Method",
    checkout_order: "Your Order",
    checkout_place: "Place Order",
    checkout_name: "Recipient name",
    checkout_phone: "Phone number",
    checkout_address: "Full address",
    checkout_city: "City",
    checkout_postal: "Postal code",
    checkout_notes: "Notes (optional)",
    checkout_bank: "Bank Transfer",
    checkout_ewallet: "E-Wallet",
    checkout_cod: "Cash on Delivery (COD)",
    checkout_success: "Order placed successfully!",

    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    actions: "Actions",
    close: "Close",
    view: "View",
    back: "Back",

    admin_login: "Admin Login",
    admin_dashboard: "Dashboard",
    admin_products: "Products",
    admin_orders: "Orders",
    admin_reviews: "Reviews",
    admin_reports: "Reports",
    admin_logout: "Log out",
    admin_revenue: "Revenue",
    admin_total_orders: "Total Orders",
    admin_active_products: "Active Products",
    admin_avg_rating: "Average Rating",
    admin_add_product: "Add Product",
    admin_edit_product: "Edit Product",
    admin_delete_product: "Delete Product",
    admin_product_name: "Product Name",
    admin_price: "Price",
    admin_stock: "Stock",
    admin_category: "Category",
    admin_status: "Status",
    admin_recent_orders: "Recent Orders",
    admin_sales_report: "Sales Report",
    admin_buyers: "Buyers",
    admin_reviewers: "Reviewers",
    admin_pending_reviews: "Pending Reviews",
    admin_desc: "Description",
    admin_code: "Code",
    admin_date: "Date",
    admin_item: "Item",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      return localStorage.getItem("wastrahub_lang") || "id";
    } catch {
      return "id";
    }
  });

  useEffect(() => {
    localStorage.setItem("wastrahub_lang", lang);
    document.documentElement.lang = lang === "id" ? "id" : "en";
  }, [lang]);

  const setLang = useCallback((next) => {
    setLangState(next === "en" ? "en" : "id");
  }, []);

  const t = useCallback(
    (key) => {
      const dict = translations[lang] || translations.id;
      return dict[key] ?? translations.id[key] ?? key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return { lang: "id", setLang: () => {}, t: (k) => k };
  }
  return ctx;
}
