<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Hapus dulu agar tidak dobel (hati-hati di production)
        // Nonaktifkan FK sementara bila perlu
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Product::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $products = $this->data();

        foreach ($products as $row) {
            Product::updateOrCreate(
                ['slug' => $row['slug']],
                $row
            );
        }

        $this->command?->info('ProductSeeder: ' . count($products) . ' produk di-seed.');
    }

    private function data(): array
    {
        // 49 produk — selaras frontend src/data/products.js
        return [
            // ========== PEKALONGAN (5) ==========
            [
                'id' => 1,
                'name' => 'Batik Pekalongan Bunga Pesisir',
                'slug' => 'batik-pekalongan-bunga-pesisir',
                'price' => 285000,
                'category_id' => 4,
                'region_id' => 1,
                'material' => 'Katun',
                'stock' => 22,
                'description' => 'Batik Pekalongan dengan motif bunga pesisir yang cerah dan hidup.',
                'image' => 'pek-bunga-pesisir.jpg',
                'technique' => 'Modern',
                'type' => 'Batik Modern',
                'status' => 'active',
            ],
            [
                'id' => 2,
                'name' => 'Batik Pekalongan Jlamprang Klasik',
                'slug' => 'batik-pekalongan-jlamprang-klasik',
                'price' => 420000,
                'category_id' => 2,
                'region_id' => 1,
                'material' => 'Katun Premium',
                'stock' => 15,
                'description' => 'Motif Jlamprang khas Pekalongan dengan proses cap yang rapi.',
                'image' => 'pek-jlamprang.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 3,
                'name' => 'Batik Pekalongan Encim Soft',
                'slug' => 'batik-pekalongan-encim-soft',
                'price' => 395000,
                'category_id' => 2,
                'region_id' => 1,
                'material' => 'Katun',
                'stock' => 18,
                'description' => 'Motif Encim dengan sentuhan lembut dan feminin.',
                'image' => 'pek-encim.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 4,
                'name' => 'Batik Pekalongan Modern Sarung',
                'slug' => 'batik-pekalongan-modern-sarung',
                'price' => 250000,
                'category_id' => 4,
                'region_id' => 1,
                'material' => 'Katun',
                'stock' => 30,
                'description' => 'Desain kontemporer dari sentra batik Pekalongan.',
                'image' => 'pek-modern-casual.jpg',
                'technique' => 'Modern',
                'type' => 'Batik Modern',
                'status' => 'active',
            ],
            [
                'id' => 5,
                'name' => 'Batik Pekalongan Buketan Printing',
                'slug' => 'batik-pekalongan-buketan-printing',
                'price' => 195000,
                'category_id' => 4,
                'region_id' => 1,
                'material' => 'Katun',
                'stock' => 40,
                'description' => 'Motif buketan khas pesisir dengan teknik printing.',
                'image' => 'pek-buketan.jpg',
                'technique' => 'Modern',
                'type' => 'Batik Modern',
                'status' => 'active',
            ],

            // ========== LASEM (4) ==========
            [
                'id' => 6,
                'name' => 'Batik Lasem Tulis Merah Darah Ayam',
                'slug' => 'batik-lasem-tulis-merah-darah-ayam',
                'price' => 980000,
                'category_id' => 1,
                'region_id' => 2,
                'material' => 'Katun Primisima',
                'stock' => 6,
                'description' => 'Batik tulis Lasem dengan warna merah darah ayam yang legendaris.',
                'image' => 'lasem-merah-darah.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 7,
                'name' => 'Batik Lasem Burung Hong',
                'slug' => 'batik-lasem-burung-hong',
                'price' => 720000,
                'category_id' => 1,
                'region_id' => 2,
                'material' => 'Katun Primisima',
                'stock' => 8,
                'description' => 'Motif burung hong (phoenix) khas Lasem.',
                'image' => 'lasem-burung-hong.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 8,
                'name' => 'Batik Lasem Latohan Cap',
                'slug' => 'batik-lasem-latohan-cap',
                'price' => 385000,
                'category_id' => 2,
                'region_id' => 2,
                'material' => 'Katun',
                'stock' => 14,
                'description' => 'Motif latohan dengan proses cap khas Lasem.',
                'image' => 'lasem-latohan.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 9,
                'name' => 'Batik Lasem Sekar Jagad Mini',
                'slug' => 'batik-lasem-sekar-jagad-mini',
                'price' => 550000,
                'category_id' => 3,
                'region_id' => 2,
                'material' => 'Katun Halus',
                'stock' => 10,
                'description' => 'Variasi Sekar Jagad versi Lasem.',
                'image' => 'lasem-sekar-jagad.jpg',
                'technique' => 'Premium',
                'type' => 'Batik Premium',
                'status' => 'active',
            ],

            // ========== BAKARAN (15) ==========
            [
                'id' => 10,
                'name' => 'Batik Bakaran Gandrung',
                'slug' => 'batik-bakaran-gandrung',
                'price' => 520000,
                'category_id' => 1,
                'region_id' => 3,
                'material' => 'Katun Primisima',
                'stock' => 10,
                'description' => 'Motif Gandrung khas Bakaran (Pati).',
                'image' => 'bak-gandrung.webp',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 11,
                'name' => 'Batik Bakaran Padas Gempal',
                'slug' => 'batik-bakaran-padas-gempal',
                'price' => 445000,
                'category_id' => 1,
                'region_id' => 3,
                'material' => 'Katun Halus',
                'stock' => 12,
                'description' => 'Motif Padas Gempal khas Bakaran.',
                'image' => 'bak-padas-gempal.webp',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 12,
                'name' => 'Batik Bakaran Magel Ati',
                'slug' => 'batik-bakaran-magel-ati',
                'price' => 480000,
                'category_id' => 1,
                'region_id' => 3,
                'material' => 'Katun Primisima',
                'stock' => 9,
                'description' => 'Motif Magel Ati khas Bakaran.',
                'image' => 'bak-magel-ati.webp',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 13,
                'name' => 'Batik Bakaran Sidomulyo',
                'slug' => 'batik-bakaran-sidomulyo',
                'price' => 650000,
                'category_id' => 3,
                'region_id' => 3,
                'material' => 'Katun Primisima',
                'stock' => 8,
                'description' => 'Motif Sidomulyo khas Bakaran.',
                'image' => 'bak-sidomulyo.webp',
                'technique' => 'Premium',
                'type' => 'Batik Premium',
                'status' => 'active',
            ],
            [
                'id' => 14,
                'name' => 'Batik Bakaran Ungker Cantel',
                'slug' => 'batik-bakaran-ungker-cantel',
                'price' => 390000,
                'category_id' => 2,
                'region_id' => 3,
                'material' => 'Katun',
                'stock' => 16,
                'description' => 'Motif Ungker Cantel khas Bakaran.',
                'image' => 'bak-ungker-cantel.webp',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 15,
                'name' => 'Batik Bakaran Udan Liris',
                'slug' => 'batik-bakaran-udan-liris',
                'price' => 425000,
                'category_id' => 2,
                'region_id' => 3,
                'material' => 'Katun Premium',
                'stock' => 14,
                'description' => 'Motif Udan Liris Bakaran.',
                'image' => 'bak-udan-liris.webp',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 16,
                'name' => 'Batik Bakaran Bregrat Ireng',
                'slug' => 'batik-bakaran-bregrat-ireng',
                'price' => 510000,
                'category_id' => 1,
                'region_id' => 3,
                'material' => 'Katun Halus',
                'stock' => 10,
                'description' => 'Motif Bregrat Ireng khas Bakaran.',
                'image' => 'bak-bregrat-ireng.webp',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 17,
                'name' => 'Batik Bakaran Mina Tani',
                'slug' => 'batik-bakaran-mina-tani',
                'price' => 365000,
                'category_id' => 2,
                'region_id' => 3,
                'material' => 'Katun',
                'stock' => 18,
                'description' => 'Motif Mina Tani khas Bakaran.',
                'image' => 'bak-mina-tani.webp',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 18,
                'name' => 'Batik Bakaran Kedelai Kecer',
                'slug' => 'batik-bakaran-kedelai-kecer',
                'price' => 340000,
                'category_id' => 2,
                'region_id' => 3,
                'material' => 'Katun',
                'stock' => 20,
                'description' => 'Motif Kedelai Kecer khas Bakaran.',
                'image' => 'bak-kedelai-kecer.webp',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 19,
                'name' => 'Batik Bakaran Manggaran',
                'slug' => 'batik-bakaran-manggaran',
                'price' => 470000,
                'category_id' => 1,
                'region_id' => 3,
                'material' => 'Katun Primisima',
                'stock' => 11,
                'description' => 'Motif Manggaran Bakaran.',
                'image' => 'bak-manggaran.webp',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 20,
                'name' => 'Batik Bakaran Sidomukti',
                'slug' => 'batik-bakaran-sidomukti',
                'price' => 580000,
                'category_id' => 3,
                'region_id' => 3,
                'material' => 'Katun Primisima',
                'stock' => 7,
                'description' => 'Sidomukti Bakaran — motif kemuliaan.',
                'image' => 'bak-sidomukti.webp',
                'technique' => 'Premium',
                'type' => 'Batik Premium',
                'status' => 'active',
            ],
            [
                'id' => 21,
                'name' => 'Batik Bakaran Merak Ngigel',
                'slug' => 'batik-bakaran-merak-ngigel',
                'price' => 720000,
                'category_id' => 1,
                'region_id' => 3,
                'material' => 'Katun Primisima',
                'stock' => 6,
                'description' => 'Motif Merak Ngigel khas Bakaran.',
                'image' => 'bak-merak-ngigel.webp',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 47,
                'name' => 'Batik Bakaran Rujak Sente',
                'slug' => 'batik-bakaran-rujak-sente',
                'price' => 395000,
                'category_id' => 2,
                'region_id' => 3,
                'material' => 'Katun',
                'stock' => 16,
                'description' => 'Motif Rujak Sente khas Bakaran.',
                'image' => 'bak-rujak-sente.webp',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 48,
                'name' => 'Batik Bakaran Pring Sedapur',
                'slug' => 'batik-bakaran-pring-sedapur',
                'price' => 455000,
                'category_id' => 1,
                'region_id' => 3,
                'material' => 'Katun Halus',
                'stock' => 11,
                'description' => 'Motif Pring Sedapur khas Bakaran.',
                'image' => 'bak-pring-sedapur.webp',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 49,
                'name' => 'Batik Bakaran Gandrung Kapirangu',
                'slug' => 'batik-bakaran-gandrung-kapirangu',
                'price' => 535000,
                'category_id' => 1,
                'region_id' => 3,
                'material' => 'Katun Primisima',
                'stock' => 8,
                'description' => 'Varian Gandrung Kapirangu khas Bakaran.',
                'image' => 'bak-gandrung.webp',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],

            // ========== YOGYAKARTA (6) ==========
            [
                'id' => 22,
                'name' => 'Batik Parang Tulis Premium',
                'slug' => 'batik-parang-tulis-premium',
                'price' => 750000,
                'category_id' => 1,
                'region_id' => 4,
                'material' => 'Katun Primisima',
                'stock' => 10,
                'description' => 'Batik tulis motif Parang premium Yogyakarta.',
                'image' => 'yog-parang-tulis.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 23,
                'name' => 'Batik Kawung Keraton Yogya',
                'slug' => 'batik-kawung-keraton-yogya',
                'price' => 680000,
                'category_id' => 1,
                'region_id' => 4,
                'material' => 'Katun Primisima',
                'stock' => 8,
                'description' => 'Motif Kawung klasik keraton Yogyakarta.',
                'image' => 'yog-kawung.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 24,
                'name' => 'Batik Truntum Yogya Cap',
                'slug' => 'batik-truntum-yogya-cap',
                'price' => 420000,
                'category_id' => 2,
                'region_id' => 4,
                'material' => 'Katun Premium',
                'stock' => 16,
                'description' => 'Motif Truntum Yogyakarta.',
                'image' => 'yog-truntum.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 25,
                'name' => 'Batik Sidomukti Yogya',
                'slug' => 'batik-sidomukti-yogya',
                'price' => 890000,
                'category_id' => 3,
                'region_id' => 4,
                'material' => 'Katun Primisima',
                'stock' => 6,
                'description' => 'Sidomukti premium Yogyakarta.',
                'image' => 'yog-sidomukti.jpg',
                'technique' => 'Premium',
                'type' => 'Batik Premium',
                'status' => 'active',
            ],
            [
                'id' => 26,
                'name' => 'Batik Yogya Sogan Klasik',
                'slug' => 'batik-yogya-sogan-klasik',
                'price' => 560000,
                'category_id' => 1,
                'region_id' => 4,
                'material' => 'Katun Halus',
                'stock' => 11,
                'description' => 'Warna sogan klasik Yogyakarta.',
                'image' => 'yog-sogan.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 27,
                'name' => 'Batik Yogya Modern Garis',
                'slug' => 'batik-yogya-modern-garis',
                'price' => 310000,
                'category_id' => 4,
                'region_id' => 4,
                'material' => 'Katun',
                'stock' => 20,
                'description' => 'Interpretasi modern motif Yogya.',
                'image' => 'yog-modern-garis.jpg',
                'technique' => 'Modern',
                'type' => 'Batik Modern',
                'status' => 'active',
            ],

            // ========== SOLO (4) ==========
            [
                'id' => 28,
                'name' => 'Batik Kawung Cap Elegan Solo',
                'slug' => 'batik-kawung-cap-elegan-solo',
                'price' => 350000,
                'category_id' => 2,
                'region_id' => 5,
                'material' => 'Katun Premium',
                'stock' => 20,
                'description' => 'Batik cap motif Kawung elegan Solo.',
                'image' => 'solo-kawung.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 29,
                'name' => 'Batik Solo Sogan Sidoluhur',
                'slug' => 'batik-solo-sogan-sidoluhur',
                'price' => 820000,
                'category_id' => 3,
                'region_id' => 5,
                'material' => 'Katun Primisima',
                'stock' => 7,
                'description' => 'Sidoluhur Solo warna sogan.',
                'image' => 'solo-sidoluhur.jpg',
                'technique' => 'Premium',
                'type' => 'Batik Premium',
                'status' => 'active',
            ],
            [
                'id' => 30,
                'name' => 'Batik Solo Truntum Cap',
                'slug' => 'batik-solo-truntum-cap',
                'price' => 395000,
                'category_id' => 2,
                'region_id' => 5,
                'material' => 'Katun',
                'stock' => 15,
                'description' => 'Truntum Solo cap.',
                'image' => 'solo-truntum.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 31,
                'name' => 'Batik Solo Parang Rusak Cap',
                'slug' => 'batik-solo-parang-rusak',
                'price' => 465000,
                'category_id' => 2,
                'region_id' => 5,
                'material' => 'Katun Premium',
                'stock' => 12,
                'description' => 'Motif Parang Rusak Solo.',
                'image' => 'solo-parang.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],

            // ========== CIREBON (3) ==========
            [
                'id' => 32,
                'name' => 'Batik Mega Mendung Exclusive',
                'slug' => 'batik-mega-mendung-exclusive',
                'price' => 1200000,
                'category_id' => 3,
                'region_id' => 6,
                'material' => 'Sutra',
                'stock' => 5,
                'description' => 'Mega Mendung exclusive Cirebon, bahan sutra.',
                'image' => 'cir-mega-mendung.jpg',
                'technique' => 'Premium',
                'type' => 'Batik Premium',
                'status' => 'active',
            ],
            [
                'id' => 33,
                'name' => 'Batik Mega Mendung Cap Biru',
                'slug' => 'batik-mega-mendung-cap-biru',
                'price' => 480000,
                'category_id' => 2,
                'region_id' => 6,
                'material' => 'Katun Premium',
                'stock' => 14,
                'description' => 'Mega Mendung cap gradasi biru.',
                'image' => 'cir-mega-cap.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 34,
                'name' => 'Batik Cirebon Wadasan',
                'slug' => 'batik-cirebon-wadasan',
                'price' => 520000,
                'category_id' => 1,
                'region_id' => 6,
                'material' => 'Katun Halus',
                'stock' => 9,
                'description' => 'Motif Wadasan khas Cirebon.',
                'image' => 'cir-wadasan.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],

            // ========== MADURA (3) ==========
            [
                'id' => 35,
                'name' => 'Batik Madura Warna Cerah',
                'slug' => 'batik-madura-warna-cerah',
                'price' => 295000,
                'category_id' => 2,
                'region_id' => 7,
                'material' => 'Katun',
                'stock' => 24,
                'description' => 'Batik Madura warna cerah dan kontras.',
                'image' => 'mad-warna-cerah.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 36,
                'name' => 'Batik Madura Tulis Bold',
                'slug' => 'batik-madura-tulis-bold',
                'price' => 580000,
                'category_id' => 1,
                'region_id' => 7,
                'material' => 'Katun Primisima',
                'stock' => 8,
                'description' => 'Batik tulis Madura karakter bold.',
                'image' => 'mad-tulis-bold.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 37,
                'name' => 'Batik Madura Modern Geometric',
                'slug' => 'batik-madura-modern-geometric',
                'price' => 245000,
                'category_id' => 4,
                'region_id' => 7,
                'material' => 'Katun',
                'stock' => 30,
                'description' => 'Interpretasi modern motif Madura.',
                'image' => 'mad-modern-geo.jpg',
                'technique' => 'Modern',
                'type' => 'Batik Modern',
                'status' => 'active',
            ],

            // ========== GARUT (3) ==========
            [
                'id' => 38,
                'name' => 'Batik Garut Alam Lembut',
                'slug' => 'batik-garut-alam-lembut',
                'price' => 340000,
                'category_id' => 2,
                'region_id' => 8,
                'material' => 'Katun',
                'stock' => 18,
                'description' => 'Motif alam Garut warna lembut.',
                'image' => 'gar-alam-lembut.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 39,
                'name' => 'Batik Garut Tulis Flora',
                'slug' => 'batik-garut-tulis-flora',
                'price' => 620000,
                'category_id' => 1,
                'region_id' => 8,
                'material' => 'Katun Halus',
                'stock' => 7,
                'description' => 'Batik tulis motif flora Garut.',
                'image' => 'gar-tulis-flora.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 40,
                'name' => 'Batik Garut Soft Pastel',
                'slug' => 'batik-garut-soft-pastel',
                'price' => 275000,
                'category_id' => 4,
                'region_id' => 8,
                'material' => 'Katun',
                'stock' => 22,
                'description' => 'Palet pastel lembut khas Garut modern.',
                'image' => 'gar-soft-pastel.jpg',
                'technique' => 'Modern',
                'type' => 'Batik Modern',
                'status' => 'active',
            ],

            // ========== BANYUMAS (3) ==========
            [
                'id' => 41,
                'name' => 'Batik Banyumas Sogan Gelap',
                'slug' => 'batik-banyumas-sogan-gelap',
                'price' => 365000,
                'category_id' => 2,
                'region_id' => 9,
                'material' => 'Katun',
                'stock' => 16,
                'description' => 'Batik Banyumas sogan gelap.',
                'image' => 'ban-sogan-gelap.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 42,
                'name' => 'Batik Banyumas Tulis Desa',
                'slug' => 'batik-banyumas-tulis-desa',
                'price' => 490000,
                'category_id' => 1,
                'region_id' => 9,
                'material' => 'Katun Primisima',
                'stock' => 9,
                'description' => 'Batik tulis Banyumas motif pedesaan.',
                'image' => 'ban-tulis-desa.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 43,
                'name' => 'Batik Banyumas Cap Harian',
                'slug' => 'batik-banyumas-cap-harian',
                'price' => 225000,
                'category_id' => 2,
                'region_id' => 9,
                'material' => 'Katun',
                'stock' => 28,
                'description' => 'Batik cap Banyumas untuk harian.',
                'image' => 'ban-cap-harian.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],

            // ========== TUBAN (3) ==========
            [
                'id' => 44,
                'name' => 'Batik Tuban Tradisional',
                'slug' => 'batik-tuban-tradisional',
                'price' => 310000,
                'category_id' => 2,
                'region_id' => 10,
                'material' => 'Katun',
                'stock' => 17,
                'description' => 'Batik Tuban corak tradisional.',
                'image' => 'tub-tradisional.jpg',
                'technique' => 'Cap',
                'type' => 'Batik Cap',
                'status' => 'active',
            ],
            [
                'id' => 45,
                'name' => 'Batik Tuban Tulis Pesisir',
                'slug' => 'batik-tuban-tulis-pesisir',
                'price' => 540000,
                'category_id' => 1,
                'region_id' => 10,
                'material' => 'Katun Halus',
                'stock' => 8,
                'description' => 'Batik tulis Tuban pengaruh pesisir.',
                'image' => 'tub-tulis-pesisir.jpg',
                'technique' => 'Tulis',
                'type' => 'Batik Tulis',
                'status' => 'active',
            ],
            [
                'id' => 46,
                'name' => 'Batik Tuban Modern Earth',
                'slug' => 'batik-tuban-modern-earth',
                'price' => 255000,
                'category_id' => 4,
                'region_id' => 10,
                'material' => 'Katun',
                'stock' => 22,
                'description' => 'Versi modern batik Tuban palet earth.',
                'image' => 'tub-modern-earth.jpg',
                'technique' => 'Modern',
                'type' => 'Batik Modern',
                'status' => 'active',
            ],
        ];
    }
}